openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /data:
    get:
      summary: 'Get data'
      description: 'Get data based on user access level'
      operationId: 'get-data'
      parameters:
        - in: 'header'
          name: 'Authorization'
          required: true
          schema:
            type: 'string'
          description: 'Authorization'
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                type: 'array'
                items:
                  type: 'object'
                  properties:
                    id:
                      type: 'integer'
                    user_id:
                      type: 'integer'
                    data:
                      type: 'string'