swagger: "2.0"
info:
  title: Title
  description: Title
  version: 1.0.0
host: www.localhost:8080
schemes:
  - http
paths:
  /data:
    get:
      description: Returns users data if called by user. Returns all data if called by admin
      security:
        - Bearer: [ ]
      responses:
        200:
          description: New response
          schema:
            type: object
            properties:
              message:
                type: string
        500:
          description: when db goes wrong
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header